apiVersion: v1
kind: Pod
metadata:
  name: s3-echoer
spec:
  serviceAccountName: s3-echoer
  containers:
  - name: main
    image: atlassian/pipelines-awscli
    command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
    env:
    - name: AWS_DEFAULT_REGION
      value: "us-east-1"
    - name: ENABLE_IRP
      value: "true"
