apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
images:
- name: amazon/aws-ebs-csi-driver
  newName: 961992271922.dkr.ecr.cn-northwest-1.amazonaws.com.cn/eks/aws-ebs-csi-driver
  newTag: v0.4.0
- name: quay.io/k8scsi/csi-provisioner
  newName: 961992271922.dkr.ecr.cn-northwest-1.amazonaws.com.cn/eks/csi-provisioner
  newTag: v1.3.0
- name: quay.io/k8scsi/csi-attacher
  newName: 961992271922.dkr.ecr.cn-northwest-1.amazonaws.com.cn/eks/csi-attacher
  newTag: v1.2.0
- name: quay.io/k8scsi/livenessprobe
  newName: 961992271922.dkr.ecr.cn-northwest-1.amazonaws.com.cn/eks/csi-liveness-probe
  newTag: v1.1.0
- name: quay.io/k8scsi/csi-node-driver-registrar
  newName: 961992271922.dkr.ecr.cn-northwest-1.amazonaws.com.cn/eks/csi-node-driver-registrar
  newTag: v1.1.0
patches:
- controller_add_snapshotter.yaml
- controller_add_resizer.yaml
resources:
- rbac_add_snapshotter.yaml
- rbac_add_resizer.yaml
- rbac_add_snapshot_controller.yaml
- snapshot_controller.yaml
